name = "App-Greple-tee"
badges = [ "github-actions/test", "metacpan" ]
authority = "cpan:UTASHIRO"

module_maker = "ModuleBuildTiny"
static_install = "auto"

[release]
branch = "main"

[FileGatherer]
exclude_match = [ '^images/.*', 'docs' ]
